name: Build TDLib

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build TDLib on Ubuntu 24.04
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout TDLib source
        uses: actions/checkout@v4
        with:
          repository: tdlib/td
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y make git zlib1g-dev libssl-dev gperf php-cli cmake clang-18 libc++-18-dev libc++abi-18-dev

      - name: Build TDLib
        run: |
          rm -rf build
          mkdir build
          cd build
          CXXFLAGS="-stdlib=libc++" CC=/usr/bin/clang-18 CXX=/usr/bin/clang++-18 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..
          cmake --build . --target install
          cd ..
          ls -l tdlib

      - name: Upload Linux TDLib artifact
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-linux
          path: tdlib/**/*

  build-windows:
    name: Build TDLib on Windows x64
    runs-on: windows-latest
    steps:
      - name: Checkout TDLib source
        uses: actions/checkout@v4
        with:
          repository: tdlib/td
          submodules: recursive

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Build TDLib
        shell: pwsh
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          git checkout bc3512a509f9d29b37346a7e7e929f9a26e66c7e
          ./bootstrap-vcpkg.bat
          ./vcpkg.exe install gperf:x64-windows openssl:x64-windows zlib:x64-windows
          cd ..

          Remove-Item build -Force -Recurse -ErrorAction SilentlyContinue
          mkdir build
          cd build
          cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build . --target install --config Release
          cd ..
          dir tdlib

      - name: Upload Windows TDLib artifact
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-windows
          path: tdlib/**
